site_name: ITMO ICT Web Development Reports
docs_dir: students

nav:
  - Home: ../README.md
  - k3341:
      - Melnikova_Nastasya:
          - Лабораторная работа 1: k3341/laboratory_works/Melnikova_Nastasya/lab1/report.md

theme:
  name: material

